package calllog;

import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.TextField;
import java.awt.event.KeyEvent;
import java.util.Hashtable;

public class MakeCallDialog extends Dialog
{
	private static final long serialVersionUID = 1L;

	public MakeCallDialog(Frame parent)
	{
		super(parent);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setFont(new Font("SansSerif", Font.PLAIN, 11));
		setSize(305,156);
		setVisible(false);
		mainPanel.setLayout(null);
		add(mainPanel);
		mainPanel.setBounds(0,0,310,148);
		destinationLabel.setText("Destination:");
		destinationLabel.setAlignment(java.awt.Label.RIGHT);
		mainPanel.add(destinationLabel);
		destinationLabel.setBounds(86,41,75,22);
		UUILabel.setText("User to User Information:");
		UUILabel.setAlignment(java.awt.Label.RIGHT);
		mainPanel.add(UUILabel);
		UUILabel.setBounds(16,66,145,22);
		mainPanel.add(destinationTextfield);
		destinationTextfield.setBounds(167,42,100,18);
		mainPanel.add(uuiTextfield);
		uuiTextfield.setBounds(167,67,100,18);
		dialButton.setLabel("Dial");
		mainPanel.add(dialButton);
		dialButton.setBackground(java.awt.Color.lightGray);
		dialButton.setBounds(87,120,64,21);
		cancelButton.setLabel("Cancel");
		mainPanel.add(cancelButton);
		cancelButton.setBackground(java.awt.Color.lightGray);
		cancelButton.setBounds(157,120,64,21);
		setTitle("Make Call with UUI");
		//}}
		destinationTextfield.setText ( lastCalledNumber );
        uuiTextfield.setText ( lastUUI );

		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		dialButton.addActionListener(lSymAction);
		cancelButton.addActionListener(lSymAction);
		SymFocus aSymFocus = new SymFocus();
		destinationTextfield.addFocusListener(aSymFocus);
		uuiTextfield.addFocusListener(aSymFocus);
		SymKey aSymKey = new SymKey();
		destinationTextfield.addKeyListener(aSymKey);
		uuiTextfield.addKeyListener(aSymKey);
		//}}
	}
		
	public MakeCallDialog(Frame parent, boolean modal)
	{
		this(parent);
        setModal(modal);
        parentFrame = parent;
	}
	
	public void addNotify()
	{
  	    // Record the size of the window prior to calling parents addNotify.
	    Dimension d = getSize();

		super.addNotify();

		if (fComponentsAdjusted)
			return;

		// Adjust components according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + d.width, insets.top + insets.bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets.left, insets.top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}

    // Used for addNotify check.
	boolean fComponentsAdjusted = false;


	

    /**
     * Shows or hides the component depending on the boolean flag b.
     * @param b  if true, show the component; otherwise, hide the component.
     * @see java.awt.Component#isVisible
     */
    public void setVisible(boolean b)
	{
		if(b)
		{
			Rectangle bounds = getParent().getBounds();
			Rectangle abounds = getBounds();
	
			setLocation(bounds.x + (bounds.width - abounds.width)/ 2,
				 bounds.y + (bounds.height - abounds.height)/2);
		}
		super.setVisible(b);
	}

	
	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == MakeCallDialog.this)
				MakeCallDialog_WindowClosing(event);
		}
	}
	
	void MakeCallDialog_WindowClosing(java.awt.event.WindowEvent event)
	{
		setVisible(false);
	}
	
   /**
    * This method collects information provided in dialog box and calls
    * the makeCall method of the CallLog class
    */
    public Hashtable<String, String> collectInfo() {
        String          calledNumber;
        String          uui;
        Hashtable<String, String>       args = new Hashtable<String, String>(3);
        
        calledNumber = destinationTextfield.getText();
        
        if(calledNumber!=null)
        {
           lastCalledNumber = new String ( calledNumber );
           args.put("calledNumber", calledNumber);
        }
        
        uui = uuiTextfield.getText();
        if(uui!=null)
        {
           lastUUI = new String ( uui );
	       args.put("uui", uui);
        }
	
        return args;
    }

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == dialButton)
				dialButton_ActionPerformed(event);
			else if (object == cancelButton)
				cancelButton_ActionPerformed(event);
		}
	}

	void dialButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		try {
			// MakeCallDialog Hide the MakeCallDialog
			this.setVisible(false);
			Hashtable<String, String> args = collectInfo();
			((CallLog)parentFrame).makeCall ( args );
			dispose();
		} catch (Exception e) {
		}
	}

	void cancelButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		try {
			this.setVisible(false);
			this.dispose();
		} catch (Exception e) {
		}
	}

	class SymFocus extends java.awt.event.FocusAdapter
	{
		public void focusLost(java.awt.event.FocusEvent event)
		{
			Object object = event.getSource();
			((TextField)object).select(0, 0);
		}

		public void focusGained(java.awt.event.FocusEvent event)
		{
			Object object = event.getSource();
			((TextField)object).selectAll();
		}
	}

	class SymKey extends java.awt.event.KeyAdapter
	{
		public void keyPressed(java.awt.event.KeyEvent event)
		{
			switch (event.getKeyCode()) {
    	        case KeyEvent.VK_ENTER:
	                dialButton_ActionPerformed( null );
	                break;
	            case KeyEvent.VK_ESCAPE:
	                cancelButton_ActionPerformed( null );
	                break;
	            default:
	                break;
	        }
		}
	}

	//{{DECLARE_CONTROLS
	java.awt.Panel mainPanel = new java.awt.Panel();
	java.awt.Label destinationLabel = new java.awt.Label();
	java.awt.Label UUILabel = new java.awt.Label();
	java.awt.TextField destinationTextfield = new java.awt.TextField();
	java.awt.TextField uuiTextfield = new java.awt.TextField();
	java.awt.Button dialButton = new java.awt.Button();
	java.awt.Button cancelButton = new java.awt.Button();
	//}}
	Frame           parentFrame;
	static String   lastCalledNumber;
    static String   lastUUI;

}
