
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapTelephonyService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface SoapTelephonyService {


    /**
     * 
     * @param localPartyIP
     * @param localPartyPort
     * @param callerLineIdentity
     * @param callDirection
     * @param agentExtension
     * @param agentId
     * @param clientConfigName
     * @param callId
     */
    @WebMethod(operationName = "CallConnected", action = "http://tempuri.org/SoapTelephonyService/CallConnected")
    @RequestWrapper(localName = "CallConnected", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CallConnected")
    @ResponseWrapper(localName = "CallConnectedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CallConnectedResponse")
    public void callConnected(
        @WebParam(name = "clientConfigName", targetNamespace = "http://tempuri.org/")
        String clientConfigName,
        @WebParam(name = "callId", targetNamespace = "http://tempuri.org/")
        String callId,
        @WebParam(name = "agentId", targetNamespace = "http://tempuri.org/")
        String agentId,
        @WebParam(name = "agentExtension", targetNamespace = "http://tempuri.org/")
        String agentExtension,
        @WebParam(name = "localPartyIP", targetNamespace = "http://tempuri.org/")
        String localPartyIP,
        @WebParam(name = "localPartyPort", targetNamespace = "http://tempuri.org/")
        Integer localPartyPort,
        @WebParam(name = "callDirection", targetNamespace = "http://tempuri.org/")
        String callDirection,
        @WebParam(name = "callerLineIdentity", targetNamespace = "http://tempuri.org/")
        String callerLineIdentity);

    /**
     * 
     * @param callId
     */
    @WebMethod(operationName = "CallHold", action = "http://tempuri.org/SoapTelephonyService/CallHold")
    @RequestWrapper(localName = "CallHold", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CallHold")
    @ResponseWrapper(localName = "CallHoldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CallHoldResponse")
    public void callHold(
        @WebParam(name = "callId", targetNamespace = "http://tempuri.org/")
        String callId);

    /**
     * 
     * @param callId
     */
    @WebMethod(operationName = "CallUnHold", action = "http://tempuri.org/SoapTelephonyService/CallUnHold")
    @RequestWrapper(localName = "CallUnHold", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CallUnHold")
    @ResponseWrapper(localName = "CallUnHoldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CallUnHoldResponse")
    public void callUnHold(
        @WebParam(name = "callId", targetNamespace = "http://tempuri.org/")
        String callId);

    /**
     * 
     * @param callId
     */
    @WebMethod(operationName = "CallDisconnected", action = "http://tempuri.org/SoapTelephonyService/CallDisconnected")
    @RequestWrapper(localName = "CallDisconnected", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CallDisconnected")
    @ResponseWrapper(localName = "CallDisconnectedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CallDisconnectedResponse")
    public void callDisconnected(
        @WebParam(name = "callId", targetNamespace = "http://tempuri.org/")
        String callId);

}
