
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapTelephonyService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.18.148.113:8000/?singlewsdl")
public class SoapTelephonyService_Service
    extends Service
{

    private final static URL SOAPTELEPHONYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPTELEPHONYSERVICE_EXCEPTION;
    private final static QName SOAPTELEPHONYSERVICE_QNAME = new QName("http://tempuri.org/", "SoapTelephonyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.18.148.113:8000/?singlewsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPTELEPHONYSERVICE_WSDL_LOCATION = url;
        SOAPTELEPHONYSERVICE_EXCEPTION = e;
    }

    public SoapTelephonyService_Service() {
        super(__getWsdlLocation(), SOAPTELEPHONYSERVICE_QNAME);
    }

    public SoapTelephonyService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPTELEPHONYSERVICE_QNAME, features);
    }

    public SoapTelephonyService_Service(URL wsdlLocation) {
        super(wsdlLocation, SOAPTELEPHONYSERVICE_QNAME);
    }

    public SoapTelephonyService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPTELEPHONYSERVICE_QNAME, features);
    }

    public SoapTelephonyService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapTelephonyService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapTelephonyService
     */
    @WebEndpoint(name = "BasicHttpBinding_SoapTelephonyService")
    public SoapTelephonyService getBasicHttpBindingSoapTelephonyService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_SoapTelephonyService"), SoapTelephonyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapTelephonyService
     */
    @WebEndpoint(name = "BasicHttpBinding_SoapTelephonyService")
    public SoapTelephonyService getBasicHttpBindingSoapTelephonyService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_SoapTelephonyService"), SoapTelephonyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPTELEPHONYSERVICE_EXCEPTION!= null) {
            throw SOAPTELEPHONYSERVICE_EXCEPTION;
        }
        return SOAPTELEPHONYSERVICE_WSDL_LOCATION;
    }

}
